### ISSUE TITLE
Install script fails on Raspbian Stretch

### ISSUE THREAD

**Issue by jasonsf** [nutechsoftware/alarmdecoder-docker#3]
Step 62/91 : RUN python manage.py initdb
 ---> Running in c1910b400c5a
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    from flask.ext.script import Manager, Command
ImportError: No module named ext.script
The command '/bin/sh -c python manage.py initdb' returned a non-zero code: 1
Failed to build docker container...

**Comment by Segfault198** [comment]
The issue is that alarmdecoder-webapp uses an older version of flask_script. flask,ext,script is deprecated. I'm currently working on a way around it.
See: https://github.com/nutechsoftware/alarmdecoder-webapp/issues/46
